export const jobsContent = {
  page: {
    title: "Job Postings",
    subtitle: "Manage your open positions",
    ctaLabel: "Create Job",
  },
  labels: {
    aiGenerated: "AI Generated",
    published: "Published",
    pendingApproval: "Pending Approval",
  },
  statusMap: {
    published: { labelKey: "published", variant: "solid" },
    pending: { labelKey: "pendingApproval", variant: "outline" },
  },
  actions: {
    create: "Create Job",
    cancel: "Cancel",
    generate: "Generate with AI",
    approve: "Approve",
    review: "Review",
  },
  actionLabels: {
    linkedin: "LinkedIn",
    indeed: "Indeed",
    edit: "Edit",
    view: "View",
    approve: "Approve",
  },
  form: {
    title: "Create New Job",
    aiToggleTitle: "Use AI to generate job description",
    aiToggleSubtitle: "AI will create a professional job description",
    fields: {
      title: { label: "Job Title", placeholder: "e.g. Senior Frontend Developer" },
      department: { label: "Department", placeholder: "e.g. Engineering" },
      location: { label: "Location", placeholder: "e.g. Remote" },
      type: { label: "Type", placeholder: "Full-time" },
    },
    descriptionLabel: "AI Generated Description",
    descriptionPlaceholder: "Click \"Generate with AI\" to create a job description",
  },
  cards: [
    {
      id: "job-1",
      title: "Senior Frontend Developer",
      tags: ["Engineering", "Remote", "Full-time"],
      description: "We are looking for a senior frontend developer...",
      candidates: 12,
      createdAt: "2026-03-15",
      aiGenerated: true,
      status: "published",
      actions: ["linkedin", "indeed", "edit", "view"],
    },
    {
      id: "job-2",
      title: "Full Stack Engineer",
      tags: ["Engineering", "San Francisco, CA", "Full-time"],
      description: "Join our team as a full stack engineer...",
      candidates: 8,
      createdAt: "2026-03-20",
      aiGenerated: false,
      status: "published",
      actions: ["linkedin", "indeed", "edit", "view"],
    },
    {
      id: "job-3",
      title: "DevOps Engineer",
      tags: ["Engineering", "Hybrid", "Full-time"],
      description: "We need an experienced DevOps engineer...",
      candidates: 0,
      createdAt: "2026-04-02",
      aiGenerated: true,
      status: "pending",
      actions: ["approve", "edit", "view"],
    },
  ],
};
