export const uiText = {
  layout: {
    welcome: (name) => `Welcome back, ${name}`,
    switchRole: "Switch role",
    dbError: "Database Connection Error",
  },
  nav: {
    hiringSettings: "Settings Of Hiring",
    system: "System",
    systemSettings: "Settings",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong.",
    empty: "No data available.",
    na: "-",
  },
  jobs: {
    title: "Job Postings",
    subtitle: "Manage your open positions",
    pageTitle: "Jobs",
    pageSubtitle: "Live data sourced from the database.",
    loading: "Loading jobs...",
    error: "Unable to load jobs.",
    empty: "No jobs found.",
    sourceBadge: "Database-driven",
    create: "Create Job",
    created: "Created",
  },
  candidates: {
    title: "Candidates",
    ofLabel: "of",
    countLabel: "candidates",
    searchPlaceholder: "Search by name or email...",
    allStages: "All Stages",
    allJobs: "All",
    allScores: "All Scores",
    scorePrefix: "Score ≥",
    loading: "Loading candidates...",
    headers: {
      candidate: "Candidate",
      role: "Role",
      stage: "Stage",
      score: "Score",
      status: "Status",
      applied: "Applied",
    },
  },
  settings: {
    systemTitle: "System Settings",
    systemSubtitle: "Roles & permissions are loaded directly from the database.",
    hiringTitle: "Settings Of Hiring",
    hiringSubtitle: "Workflow settings for the hiring pipeline.",
    rolesTitle: "Roles & Permissions",
    loadingRoles: "Loading roles...",
    rolesError: "Unable to load roles.",
    table: {
      role: "Role",
      permissions: "Permissions",
    },
  },
  placeholders: {
    subtitle: "Placeholder content. TODO: connect to backend module.",
    body: "Ready for future integration.",
    assignmentsTitle: "Assignments",
    interviewsTitle: "Interviews",
    offersTitle: "Offers",
  },
  dashboard: {
    loading: "Loading dashboard...",
    pipelineEmpty: "No pipeline statuses available.",
    pipelineSuffix: "Pipeline",
    pipelineCountLabel: "candidates",
    approvalsTitle: "Pending Approvals",
    approvalsEmpty: "No approval statuses available.",
    approve: "Approve",
    review: "Review",
    activityTitle: "Recent Activity",
    activityEmpty: "No activity statuses available.",
    pipelineFooter: "Total in pipeline",
  },
};
